version: '3.3'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 