version: '3.3'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: darkchat-backend
    ports:
      - "8000:8000"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud  # Mount gcloud credentials
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/root/.config/gcloud/application_default_credentials.json}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-octopus-449307}
    restart: unless-stopped
    healthcheck:
      test: python -c "import urllib.request; urllib.request.urlopen('http://34.45.129.121:8000/')"
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: darkchat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3 